# Form implementation generated from reading ui file 'stats_window.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_StatsForm(object):
    def setupUi(self, StatsForm):
        StatsForm.setObjectName("StatsForm")
        StatsForm.resize(512, 800)
        StatsForm.setMinimumSize(QtCore.QSize(512, 800))
        StatsForm.setMaximumSize(QtCore.QSize(512, 800))
        self.pie_chart_label = QtWidgets.QLabel(parent=StatsForm)
        self.pie_chart_label.setGeometry(QtCore.QRect(90, 10, 321, 261))
        self.pie_chart_label.setText("")
        self.pie_chart_label.setPixmap(QtGui.QPixmap("../../oboi/magnific-AgLAmq47IbKpxEoCaTFg-photo_5319043127962624274_y.png"))
        self.pie_chart_label.setObjectName("pie_chart_label")
        self.info = QtWidgets.QTableWidget(parent=StatsForm)
        self.info.setGeometry(QtCore.QRect(20, 400, 471, 381))
        self.info.setObjectName("info")
        self.chart_type_box = QtWidgets.QComboBox(parent=StatsForm)
        self.chart_type_box.setGeometry(QtCore.QRect(170, 280, 161, 26))
        self.chart_type_box.setObjectName("chart_type_box")

        self.retranslateUi(StatsForm)
        QtCore.QMetaObject.connectSlotsByName(StatsForm)

    def retranslateUi(self, StatsForm):
        _translate = QtCore.QCoreApplication.translate
        StatsForm.setWindowTitle(_translate("StatsForm", "Form"))
