# Form implementation generated from reading ui file 'notifications_window.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_NotificationsForm(object):
    def setupUi(self, NotificationsForm):
        NotificationsForm.setObjectName("NotificationsForm")
        NotificationsForm.resize(512, 800)
        self.listView = QtWidgets.QListView(parent=NotificationsForm)
        self.listView.setGeometry(QtCore.QRect(30, 110, 451, 651))
        self.listView.setObjectName("listView")
        self.checkBox = QtWidgets.QCheckBox(parent=NotificationsForm)
        self.checkBox.setGeometry(QtCore.QRect(36, 50, 371, 41))
        font = QtGui.QFont()
        font.setPointSize(42)
        self.checkBox.setFont(font)
        self.checkBox.setIconSize(QtCore.QSize(32, 32))
        self.checkBox.setObjectName("checkBox")

        self.retranslateUi(NotificationsForm)
        QtCore.QMetaObject.connectSlotsByName(NotificationsForm)

    def retranslateUi(self, NotificationsForm):
        _translate = QtCore.QCoreApplication.translate
        NotificationsForm.setWindowTitle(_translate("NotificationsForm", "Form"))
        self.checkBox.setText(_translate("NotificationsForm", "  Уведомления"))
